config/routes.rb
Rails.application.routes.draw do
  resources :results
  get 'payments/checkout'

resources :contactus
devise_for :users, :controllers => { :registrations => "registrations"}
resources :products do
	resources :comments
end
		get 'home/ContactUs'
	get 'home/Login'
get 'home/Store'
get 'home/blogs'
get 'home/index'
	resources :home
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/product - Copy.rb
class Product < ApplicationRecord
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :user
	has_many :taggings, dependent: :destroy
	has_many :tags, through: :taggings
	has_many :comments, dependent: :destroy

	has_attached_file :img_url, styles: { large: "800x600>", medium: "320x200>", thumb: "100x80#" }, validate_media_type: false
  	validates_attachment_content_type :img_url, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	def self.tagged_with(name)
		Tag.find_by!(name: name).products
	end

	def all_tags=(names)
		# names="music, spotify"
		self.tags = names.split(',').map do |name|
			Tag.where(name: name).first_or_create!
		end
	end
	def all_tags
		tags.map(&:name).join(", ")
	end
end

app/models/result.rb
class Result < ApplicationRecord
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings, dependent: :destroy
	has_many :products, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :product
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :products
end

app/models/video.rb
class Video
  attr_accessor :raw_result

  def url
    "https://www.youtube.com/watch?v=#{video_id}"
  end

  def video_id
    raw_result.id.videoId
  end

  def title
    raw_result.snippet.title
  end
    
      def embedded_code
    %{
    <iframe width="560" height="315" src="#{embed_url}" frameborder="0" allowfullscreen></iframe>
    }
  end

  def embed_url
    "https://www.youtube.com/embed/#{video_id}"
  end
end

app/models/youtube_search.rb
require 'google/api_client'

class YoutubeSearch
  # Please use your own API key and enable the Youtube API for it
  # This default key is provided for your convenience but it will be invalid soon
  # On Heroku, you can set `heroku config:set GOOGLE_API_KEY=your-key-value
  # On localhost, you can set the GOOGLE_API_KEY ENV variable or use the dotenv gem
  DEVELOPER_KEY = ENV['GOOGLE_API_KEY'] || 'AIzaSyDHHaSqaRPFqjbkF9Av-2f8RWWpEBHMVe8'
  YOUTUBE_API_SERVICE_NAME = 'youtube'
  YOUTUBE_API_VERSION = 'v3'

  attr_reader :youtube, :client, :videos, :playlists, :channels

  def initialize
    get_service
  end

  def get_service
    @client = Google::APIClient.new(
      :key => DEVELOPER_KEY,
      :authorization => nil,
      :application_name => $PROGRAM_NAME,
      :application_version => '1.0.0'
    )
    @youtube = @client.discovered_api(YOUTUBE_API_SERVICE_NAME, YOUTUBE_API_VERSION)

    return @client, @youtube
  end
    def youtube
        @youtube
    end
    def client
        @client
    end
  # return a list of Result instances
  def search(query)
        @search = {}
    return @search[query] if @search[query]

    search_response = client.execute!(
      :api_method => youtube.search.list,
      :parameters => {
        :part => 'snippet',
        :q => query,
        :maxResults => max_result,
      }
    )
      @search[query]=search_response.data.items
      @videos=[]
      @channels=[]
      @playlists=[]
      @search[query].each do |search_result|
          case search_result.id.kind
              when 'youtube#video'
              video=Video.new
              video.raw_result=search_result
              @videos << video
              when 'youtube#channel'
              @channels << search_result
              when 'youtube#playlist'
              @playlists << search_result
          end
      end
      @search[query]
  end
   

  def max_result
    5
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@product=Product.find(params[:product_id])
		@comment=@product.comments.create(params[:comment].permit(:body))
		redirect_to product_path(@product)
	end

	def destroy
		@product=Product.find(params[:product_id])
		@comment=@product.comments.find(params[:id])
		@comment.destroy
		redirect_to product_path(@product)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def Login
    render "Login"
    @home = Home.new
    # @Home= Home.find(params[:id])

  end
  def Store
    render "Store"
  end
  def ContactUs
    render "ContactUs"
    @home = Home.all
    # @Home = Home.find(params[:id])
  end

  def blogs
    # @Home= Home.find(params[:id])
  end
  def create
    @home = Home.new(Home_params)
    if @home.save
      redirect_to @Home
    else
      render'index'
    end
  end
  def index
    @home=Home.all
  end
  def show
    @home= Home.find(params[:id])
  end

  private
  def home_params
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def checkout
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
    before_filter :initialize_cart
  def index
      query=params[:q]
        @youtube_search=YoutubeSearch.new
      @youtube_search.search query
      @videos=@youtube_search.videos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contactus_helper.rb
module ContactusHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/comments/_comment.html.erb
<% if user_signed_in?%>
<h2 style="text-transform: uppercase; color: #fff;font-size: 2rem; padding-top: 10px;">
<%= current_user.name %></h2>
<%else%>
<h2 style="text-transform: uppercase; color: #fff;font-size: 2rem; padding-top: 10px;">
U NEED TO LOGIN TO SEE THIS USER</h2>
<%end%>
<p style=" color: #fff;"><%= comment.body %></p>
<p style=" color: #fff;"><%= time_ago_in_words(comment.created_at)%></p>
<% if user_signed_in?%>
<% if @product.user == current_user || current_user.admin?%>
<p><%= link_to 'Delete',[comment.product,comment], method: :delete, data: { confirm: 'Are you sure?' } %>
<hr>
<%end%>
<%end%>
</p>

app/views/comments/_form.html.erb
<%= form_for([@product,@product.comments.build]) do |f| %>
	<p>
		<%= f.text_area :body, :style=>"height: auto;width: 100%;text-overflow: inherit;border-radius: 6px;" %>
	</p>
	<br>
	<p style="margin-top: -25px;">
		<%= f.submit :Submit, :style=>"width:100%;background-color: rgb(10, 245, 61);padding: 2px 2px 2px 2px;border-radius: 6px;border: 1px solid rgba(255,255,255,0.9);color: #fff;"%>
	</p>
<%end%>

app/views/home/index.html.erb
<!DOCTYPE HTML>
<html>
<head>
<title>Home</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	 	<!---strat-slider-->
			<script type="text/javascript">
				$(function() {
				
					$('#da-slider').cslider({
						autoplay	: true,
						bgincrement	: 450
					});
				
				});
			</script>
		<!---//strat-slider-->
		 <!-- scroll -->
		 <script type="text/javascript">
			$(document).ready(function() {
			
				var defaults = {
		  			containerID: 'toTop', // fading element id
					containerHoverID: 'toTopHover', // fading element hover id
					scrollSpeed: 1200,
					easingType: 'linear' 
		 		};
				
				
				$().UItoTop({ easingType: 'easeOutQuart' });
				
			});
		</script>
		 <!-- //scroll -->	
			<!-- start portfolios -->
		<script type="text/javascript">
			$('body').flipLightBox()
		</script>
		<script type="text/javascript">
			$(function() {

				var filterList = {

					init : function() {

						// MixItUp plugin
						// http://mixitup.io
						$('#portfoliolist').mixitup({
							targetSelector : '.portfolio',
							filterSelector : '.filter',
							effects : ['fade'],
							easing : 'snap',
							// call the hover effect
							onMixEnd : filterList.hoverEffect()
						});

					},

					hoverEffect : function() {

						// Simple parallax effect
						$('#portfoliolist .portfolio').hover(function() {
							$(this).find('.label').stop().animate({
								bottom : 0
							}, 200, 'easeOutQuad');
							$(this).find('img').stop().animate({
								top : -40
							}, 500, 'easeOutQuad');
						}, function() {
							$(this).find('.label').stop().animate({
								bottom : -40
							}, 200, 'easeInQuad');
							$(this).find('img').stop().animate({
								top : 0
							}, 300, 'easeOutQuad');
						});

					}
				};

				// Run the show!
				filterList.init();

			});
		</script>
	<!-- popup -->
				<script>
					$(document).ready(function() {
						$('.popup-with-zoom-anim').magnificPopup({
							type: 'inline',
							fixedContentPos: false,
							fixedBgPos: true,
							overflowY: 'auto',
							closeBtnInside: true,
							preloader: false,
							midClick: true,
							removalDelay: 300,
							mainClass: 'my-mfp-zoom-in'
					});
				});
				</script>
  <script type="text/javascript">
    $(function() {
        $('#portfoliolist a').lightBox();
    });
   </script>
 <!-- nav -->  
<script type="text/javascript">
$(document).ready( function() {
    $('.subMenu').smint({
    	'scrollSpeed' : 1000
    });
});
</script>
<script>
window.addEventListener("load",function() {
  setTimeout(function(){
    window.scrollTo(0, 1);
  }, 0);
});</script>
</head>
<body>
	<!-- start slider -->
	<div class="parent">
<div style="margin-top: 9%;position: absolute;width: 100%;;text-align: center;">
<% if user_signed_in?%>
<a style="font-family: lucida;font-size: 50px;color: white;background: none;">Welcome <%= current_user.name%></a>
<%end%>
</div>
<div id="search-bar">
<%= form_tag products_path, :action=>"index", :method=>"get" do %>
<%= text_field_tag :tag, params[:tag], :name=>"Search", :placeholder=>"   Search Anything", :id=>"s-bar" %>
<%= submit_tag "Search",:name=>"Search", :value=>"Search", :style=>"width: 100px; border: none; background: #eee; font-size: 25px; position: relative; top: 5px; display: none;"%>
<%end%>
</div>



<div class="slider_bg s7">
	<%= image_tag("bg2.jpg")%>
 </div>
</div>
 <a  href="#services" class="button scroll"><%= image_tag("arrow.png")%></a>	
 	<!--start header -->
 	<div class="header">
 		<div class="logo">
 			<a  href="#s7" class="scroll"><%= image_tag("logo_here.jpg")%></a>
 		</div>




		<!-- start top-nav-->
		<nav>
		<div class="h_right">	
			<center>
		<div id="nav" class="subMenu" >
			
			<div class="wrap">
				
		 	 	<div class="inner" >
		 	 		<ul>
		 			<li id="s" class="subNavBtn"><%=link_to "SERVICES",home_blogs_path%></li>
					<li id="s" class="subNavBtn"><%=link_to "PROJECTS",home_blogs_path%></li>
					<li id="s" class="subNavBtn"><%=link_to "ABOUT US",home_blogs_path%></li>
					<li id="s" class="subNavBtn"><%=link_to "STORE",products_path%></li>
					<li id="s" class="subNavBtn"><%=link_to "BLOGS",home_blogs_path%></li>
					<li id="s" class="subNavBtn end"><%=link_to "VECTORS",products_path%></li>
					<li id="s" class="subNavBtn"><%=link_to "CONTACT",contactus_path%></li>
					</ul>
			  	</div>
			  	<div id="ll">
			   <!-- /.navbar-collapse -->
			   <% if user_signed_in?%>
			   <a class="btn btn-dark btn-lg"><%= link_to "LOGOUT", destroy_user_session_path, :method => :delete %></a>
			   <%else%>
	             	<a class="btn btn-dark btn-lg" data-target="#myModaltask" data-toggle="modal"><%=image_tag("logo-login.png" , :class => "style_image")%></a>
	             	<%end%>
	             	<a class="btn btn-dark btn-lg"><span class="search-btn"><%=image_tag("search-img.png" , :class => "style_image")%></span></a>
	       
	             	<div>
	                <div class="clearfix"> </div>	
	    	</div>	
	    	</center>
	   	</div>
	   </nav>
	   <div id="sidelinks">
	<a href="http://www.fb.com/" target="_blank"><%= image_tag("facebook.png", :id =>"sideicons1")%></a><br>
	<a href="http://www.whatsapp.com/" target="_blank"><%= image_tag("whatsapp.png", :id =>"sideicons2")%></a><br>
	<a href="http://www.google.com/" target="_blank"><%= image_tag("google-plus.png", :id =>"sideicons3")%></a><br>
	<a href="http://www.instagram.com/" target="_blank"><%= image_tag("instagram.png", :id =>"sideicons4")%></a>
</div>

<div class="modal fade" id="myModaltask" role="dialog">
<div class="modal-dialog modal-md">
<div class="modal-content">
<div class="modal-header" style="background-color:#5B90F6;border-radius: 5px 5px 0px 0px;box-shadow: 0px 4px 10px #666; text-align:center;"><button class="close" data-dismiss="modal" type="button">×</button>

<h2 class="modal-title" style="color:#FFFFFF;">OPTIONS</h2>
</div>
<div style="padding: 50px;padding-bottom: 5px;">
<a><%=link_to "LOGIN",new_user_session_path, :style=>"background-color: #337ab7;border-radius: 6px;padding: 10px;color: white;margin: 110px;"%></a>
<a><%=link_to "SIGNUP",new_user_registration_path, :style=>"background-color: #337ab7;border-radius: 6px;padding: 10px;color: white;"%></a>
<div class="modal-footer" style="margin-top: 35px;"><button class="btn btn-primary" data-dismiss="modal" type="button">Close</button></div>
</div>
</div>
</div>





<!-- 

<div id="links">
<span class="nav-btn">MENU</span>
<div id="site-links">
   <ul id="navin">
    <li><a href="#" id="main-link">Home</a></li>
	<li><a href="#" id="main-link">Updates</a></li>
	<li><a href="#" id="main-link">Data</a></li>
	<li><a href="#" id="main-link">Datesheet</a></li>
	<li><a href="#" id="main-link">Contact</a></li>
	<li><span class="search-btn"><%=image_tag("search-img.png" , :class => "style_image")%></span></li>
   </ul>
 -->
<script>
$('span.search-btn').click(function(){
	$('#search-bar').slideToggle();
})
</script>
<script>
$('span.nav-btn').click(function(){
	$('#navin').slideToggle();
})
</script>
</div>
</div>

			<!-- start smart_nav * -->
		 	<nav class="nav">
	            <ul class="nav-list">
	                <li class="nav-item"><a href="#services">Services</a></li>
	                 <li class="nav-item"><a href="#work" class="scroll">Services</a></li>
	                  <li class="nav-item"><a href="#about" class="scroll">About us</a></li>
	                   <li class="nav-item"><a href="#blog" class="scroll">Blogs</a></li>
	                <li class="nav-item"><a href="#studio" class="scroll">Photos</a></li>
	                <li class="nav-item"><a href="#pricing" class="scroll">Login</a></li>	            	               
	                <li class="nav-item"><a href="#contact"  class="scroll">Contact</a></li>
	                <div class="clear"></div>
	            </ul>
	    	</nav>
			<!-- end smart_nav * -->
		</div>
		<div class="clear"></div>
	  </div>
<!---//End-header-->	

   		        <!--start-bottom-footer-->
				<div class="bottom-footer">
					<div class="wrap"> 
						<div class="bottom-footer-center">
							<ul class="bottom-social-icons">
								<li><a class="bottom-twitter" href="#"> </a></li>
								<li><a class="bottom-facebook" href="#"> </a></li>
								<li><a class="bottom-pin" href="#"> </a></li>
								<li><a class="bottom-google" href="#"> </a></li>
								<div class="clear"> </div>
							</ul>
						</div>	
						<div class="bottom-footer-left">
							<p><span>&#169; Copyright 2017</span></a></p>
						</div>		  
						<div class="clear"> </div>
					</div>
				</div>
				<!--//End-bottom-footer-->
 <!-- scroll_top_btn -->
		<script type="text/javascript">
		jQuery(document).ready(function($) {
			$(".scroll").click(function(event){		
				event.preventDefault();
				$('html,body').animate({scrollTop:$(this.hash).offset().top},1200);
			});
		});
	</script>

		 <a href="#da-slider" id="toTop" style="display: block;"><span id="toTopHover" style="opacity: 1;"></span></a>
</body>
</html>

app/views/results/_index.html.erb
<body style="background-image:url(<%= asset_path 'images/new.jpg' %>);">
<h1 style="color: #00e2ff;font-family: initial;margin-left: 20px;-webkit-text-stroke: 1px black;font-size:2em;font-weight:bolder;"><center>Youtube  Videos Search</center></h1><br>
<center>
<%= form_tag nil, method: 'get', class: 'form-inline', style: 'margin-bottom: 20px' do %>
 <div class="form-group" style="width:20%;">
    <%= text_field_tag :q, :style=>"height: auto;width: 50%;text-overflow: inherit;border-radius: 6px;"%>
     </div>
     <br>
     <div class="form-group">
    <%= submit_tag "Search", class: 'btn btn-success btn-lg' %>
    </div>
<% end %>
</center><br>
   
          <div class="panel panel-default panel-list" style="width:70%;margin:20px auto;">
          <div class="panel-heading">
            <h3 class="panel-title"><center>Your Searched Videos</center></h3>
        </div>
          <div class="panel-body">
            <% @videos.each do |video|%>
                <%= video.title%><br><br>
              <%=raw video.embedded_code%>
            <div style="border:solid 1px black;margin-top:40px;margin-bottom:40px;" ></div>
          <%end%>
          </div>
    </div>
</body>